### ISSUE TITLE
A release candidate for AmberTools23 is now available

### ISSUE THREAD

**Issue by dacase** [conda-forge/ambertools-feedstock#97]
### Comment:

@jaimergp The first release candidate for AmberTools23 is now available:

wget https://ambermd.org/downloads/AmberTools23_rc1.tar.bz2

Are you (or someone else connected to this github page) still able and willing to work on this?
You could skip this RC if you wish...a second one should be ready in a week or so.  Let me know what I can do to help out.

One change from AmberTools22 is that the NAB compiler is no longer a part of the package.  This should be a simplification, and means that users no longer need to the compilers as well as the ambertools package itself.

**Comment by jaimergp** [comment]
Hey! Yes, we can start trying out the RCs. My time budget is limited for this kind of task but we'll manage somehow. It would really help if someone on the Amber team would be willing to help set up new PRs (I can review) or at least post issues (tagging me) for the patch updates and so on.

**Comment by mattwthompson** [comment]
Thanks for making an RC available. I've given it a spin on some of our infrastructure and nothing is obviously broken. (We only use a tiny portion of AmberTools, so this doesn't necessarily say much, but it says marginally more than nothing.)

https://github.com/openforcefield/openff-toolkit/actions/runs/4862595919?pr=1599

**Comment by mattwthompson** [comment]
I'm able to run @dacase's block above and am reporting back what happens:

```shell
$ echo $AMBERHOME                                                                                                       10:06:40
/Users/mattthompson/mambaforge/envs/AmberTools23rc
$ echo $PATH                                                                                                            10:06:45
/Users/mattthompson/micromamba/bin:/usr/local/opt/libarchive/bin:/usr/local/opt/libarchive/bin:/usr/local/opt/openssl/bin:/usr/local/sbin:/Users/mattthompson/mambaforge/envs/AmberTools23rc/bin:/Users/mattthompson/mambaforge/condabin:/Users/mattthompson/bin:/usr/local/bin:/usr/local/bin:/usr/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
$ echo $PYTHONPATH                                                                                                      10:06:52

$  echo $LD_LIBRARY_PATH                                                                                                 10:06:54

```
This is on Apple Silicon with Mambaforge dated a few weeks ago. I'm not sure what's supposed to happen (`$PYTHONPATH` is very arcane - is AmberTools using it?) but common executables are available as I'd expect:

```shell
$ which antechamber && which sander                                                                                     10:08:13
/Users/mattthompson/mambaforge/envs/AmberTools23rc/bin/antechamber
/Users/mattthompson/mambaforge/envs/AmberTools23rc/bin/sander

**Comment by hainm** [comment]
> The AmberTools23_rc install seems slightly different from AmberTools22. I did this:
> 
> ```
> conda create --name AmberTools23rc
> conda activate AmberTools23rc
> conda install -c conda-forge/label/ambertools_rc -c conda-forge ambertools
> conda deactivate
> conda activate AmberTools23rc
> ```
> 
> After this, $AMBERHOME is set to `~/.conda/envs/AmberTools23rc`, but the $AMBERHOME/amber.sh script has not been run, so that PATH, PYTHONPATH and LD_LIBRARY_PATH variables are not set for AmberTools. In AmberTools22, the step of `source $AMBERHOME/amber.sh` was done upon conda activation, as far as I can tell.
> 
> Does anyone else see this behavior? It might be specific to my setup (Intel python), or might be operator error (although I've tried several times, but all on the same machine.)
> 
> Beyond this, everything I've tried in AmberTools23rc seems to be working as expected. If one or two others (@swails ?) can explore a bit, we may be able to promote this to the real conda-forge channel.

@dacase FYI: When I was working with ambertools conda, the amber.sh was never needed.

**Comment by swails** [comment]
PYTHONPATH is not needed for a conda build since it's added to a location automatically searched for imports by the Python interpreter, so `conda activate` will never set it.  Neither is `LD_LIBRARY_PATH` or any of its friends (like `DYLD_*`) -- conda automatically sets the rpath for libraries so they'll be properly resolved at runtime on any platform.

You can see everything that's set when you activate an environment with ambertools installed by [looking here](https://github.com/conda-forge/ambertools-feedstock/blob/main/recipe/activate.sh).

I suspect that your LD_LIBRARY_PATH and PYTHONPATH environment variables are being set from a previously-sourced amber.sh from a local Amber build.

**Comment by swails** [comment]
> where and how is $AMBERHOME/bin added to the PATH?

`$AMBERHOME` is set to the conda prefix directory for the conda environment that ambertools is installed into.  `${CONDA_PREFIX}/bin` is where *all* of the binaries for that conda environment are put, so that directory is added to PATH as part of `conda activate <environment>`.

Specifically, after you activate an environment with ambertools installed, it should look something like this:

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/779022/235989003-b5b239fa-c486-4335-913c-453e63920adb.png">

where `$AMBERHOME` is the path to the conda environment (rather than, say, a source installation you've checked out locally).

I have no idea why the conda environment's bin directory wouldn't be added to your PATH...

> So, this PATH problem led me to look at `amber.sh`, which _is_ included in the conda package, but doesn't seem(?) be needed. This was the origin of my confusion.

This file should not be used in conda installs.  It's an artifact generated by the standard Amber build process and wasn't deleted.  It's more that this file wasn't excluded, rather than was included.

**Comment by jaimergp** [comment]
> @jaimergp Are we ready to publish this to the regular conda-forge channel. The problems listed above are probably specific to me, and I haven't found any problems with the release candidate package.

Yea, let's open that PR. Do you have a link for the final source tarball?

**Comment by mmfarrugia** [comment]
Hello,

I stumbled upon this as I was trying to troubleshoot some issues with nab.  The research group I'm in relies on it for some analyses, particularly Hessian calculations, so I'm disappointed to see it will no longer be included in AmberTools23 but curious if it will be available as a stand-alone package on conda-forge moving forward?  

Additionally, I thought I'd notify you that the [AmberTools23 page](http://ambermd.org/AmberTools.php)  and Amber23 manual still seem to indicate nab is included, but perhaps I misunderstood and it's only sff which is in the same folder as the excluded nab code, thus nabc/sff?  So far, this is the only place where I was able to verify that I hadn't botched my conda install of ambertools23 so I thought I'd suggest clarifying that on the amermd.org hosted site and related tutorials for anyone else who is still using it but not code-savvy enough to look through github or check their conda environment files.

Lastly, I am running into a gcc compiler issue when trying to use older versions of ambertools so that I can use nab. I have already troubleshooted the gcc conda install so I thought I'd ask if and where the nab code will continue to be maintained so I can submit an issue to the correct repo/email/forum?

Thank you for your work on an indispensable set of tools,

Mikaela

**Comment by jaimergp** [comment]
Hi Mikaela, AT22 should still have nab. Maybe you can create a separate environment for AT22 and point you workflow to the absolute path of nab in that environment?

**Comment by mmfarrugia** [comment]
Hi Jaime,

Yeah, I have been attempting to use it with AT22 but am running into a gcc compiler issue. I think I have managed to get around it for now by forcing all my packages to come from conda-forge and not installing any other packages. Inconvenient as I will eventually need it to play nice with other packages but I can create an egg for that and this seems to be an issue bigger than just ambertools.

 I would still be curious to know if nab will no longer receive support or be included in any future packages so that we can begin to plan for a replacement if necessary.

Thank you for such a quick reply!

Mikaela

**Comment by jaimergp** [comment]
All my notes mention that `nab` was removed in AT23, but I'll let @dacase comment first hand.

**Comment by mmfarrugia** [comment]
I agree that the nabc repo will be the best starting point, particularly as I'd like to make my solution simple and maintainable so it sounds like it is best to move away from nab regardless of whether I can troubleshoot the configuration. Thank you for the recommendation and the more detailed overview of why nab is being retired as well as the pointer to tnmode.c.  All are extremely helpful, thank you.

The compilation issues do remain after switching to nabc, but are different and seem specific to the files available on the repo so I have submitted an issue to that repo but I am quite rusty on my C so I hope I haven't missed something trivial.  

Thank you again for your swift support in using the force field routines.

Mikaela Farrugia
